@startuml foco
class usuario
class foco {
    -EstadoFoco estado 
    + Encender ()
    + Apagar ()
    +LeerEstado() : EstadoFoco

}
 
 class EstadoFoco

Usuario o-- Foco 
Foco *--EstadoFoco
EstadoFoco --|>Booleano
 
 @enduml

